"use strict";
let estaChovendo = false;
estaChovendo = true;
let idade = 30;
let altura = 1.64;
const nacionalidade = 'brasileira';
const colegas = ['lucas', 'fernanda'];
const tecnologias = ['html', 'css', 'js'];
const notas = [7, 9, 5, 8];
const lista = ['bianca', true, 30];
let idadeDaAna = 31;
idadeDaAna = '31 anos';
let dadosDaApi;
dadosDaApi = 10;
dadosDaApi = true;
dadosDaApi = [1, 2, 3];
dadosDaApi = 'string';
let curso = 'front-end';
